version: '3.8'

services:
  web:
    build: .
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_NAME_FILE: /run/secrets/MYSQL_DATABASE
      DB_USER_FILE: /run/secrets/MYSQL_USER
      DB_PASS_FILE: /run/secrets/MYSQL_PASSWORD
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER_FILE: /run/secrets/PMA_USER
      PMA_PASSWORD_FILE: /run/secrets/PMA_PASSWORD
    networks:
      - app-network
    secrets:
      - PMA_USER
      - PMA_PASSWORD

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_USER:
    file: ./secrets/MYSQL_USER.txt
  MYSQL_PASSWORD:
    file: ./secrets/MYSQL_PASSWORD.txt
  MYSQL_DATABASE:
    file: ./secrets/MYSQL_DATABASE.txt
  PMA_USER:
    file: ./secrets/PMA_USER.txt
  PMA_PASSWORD:
    file: ./secrets/PMA_PASSWORD.txt
